//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion_de_asp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proveedor()
        {
            this.producto = new HashSet<producto>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "El campo nombre debe ser obligatorio")]

        public string nombre { get; set; }
        [Required(ErrorMessage = "El campo direccion debe ser obligatorio")]

        public string direccion { get; set; }
        [Required(ErrorMessage = "El campo telefono debe ser obligatorio")]

        public string telefono { get; set; }
        [Required(ErrorMessage = "El campo nombre de contacto debe ser obligatorio")]

        public string nombre_contacto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto { get; set; }
    }
}
